- https://www.census.gov/library/visualizations/2012/dec/c2010sr-01-density.html

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from tqdm.autonotebook import tqdm
from postdocsalary.paths import DATA_DIR, ensure_dir
import urllib.request

<ipython-input-3-37777429a894>:5: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

In [5]:
CSA_pop = pd.read_csv(DATA_DIR / 'statistical_areas' / 'CSA_pop.csv')

In [7]:
CSA_pop[:20]

,CBSA Code,CBSA title,Population 2000,Population 2010,Percent change in population,Population-weighted density 2000,Population-weighted density 2010,Numeric change in population-weighted density 2000 to 2010
0,NaN,Average of all U.S. metro areas,"636,830","705,786",10.8,"6,725.4","6,320.8",-404.6
1,NaN,"Average of U.S. metro areas of 5,000,000 or more","7,711,676","8,431,848",9.3,"14,229.7","13,328.3",-901.4
2,NaN,"Average of U.S. metro areas of 2,500,000 to 4,...","3,177,519","3,522,237",10.8,"5,838.5","5,549.9",-288.7
3,NaN,"Average of U.S. metro areas of 1,000,000 to 2,...","1,449,479","1,631,131",12.5,"3,685.7","3,489.4",-196.3
4,NaN,"Average of U.S. metro areas of 500,000 to 999,999","621,465","699,135",12.5,"3,015.1","2,985.5",-29.6
5,NaN,"Average of U.S. metro areas of 250,000 to 499,999","315,470","350,299",11.0,"2,392.7","2,321.4",-71.3
6,NaN,"Average of U.S. metro areas of less than 250,000","134,599","147,527",9.6,"1,615.9","1,597.0",-19.0
7,10180.0,"Abilene, TX Metro Area","160,245","165,252",3.1,"1,903.0","1,771.8",-131.2
8,10420.0,"Akron, OH Metro Area","694,960","703,200",1.2,"2,682.9","2,412.8",-270.1
9,10500.0,"Albany, GA Metro Area","157,833","157,308",-0.3,952.4,922.7,-29.7
10,10580.0,"Albany-Schenectady-Troy, NY Metro Area","825,875","870,716",5.4,"2,858.6","2,944.9",86.3
11,10740.0,"Albuquerque, NM Metro Area","729,649","887,077",21.6,"3,310.2","3,518.6",208.4
12,10780.0,"Alexandria, LA Metro Area","145,035","153,922",6.1,845.0,803.2,-41.8
13,10900.0,"Allentown-Bethlehem-Easton, PA-NJ Metro Area","740,395","821,173",10.9,"3,643.6","3,889.3",245.7
14,11020.0,"Altoona, PA Metro Area","129,144","127,089",-1.6,"2,755.7","2,428.7",-327.0
15,11100.0,"Amarillo, TX Metro Area","226,522","249,881",10.3,"2,743.6","2,591.4",-152.2
16,11180.0,"Ames, IA Metro Area","79,981","89,542",12.0,"2,382.0","2,343.4",-38.6
17,11260.0,"Anchorage, AK Metro Area","319,605","380,821",19.2,"2,930.5","3,006.9",76.4
18,11300.0,"Anderson, IN Metro Area","133,358","131,636",-1.3,"1,524.6","1,327.9",-196.8
19,11340.0,"Anderson, SC Metro Area","165,740","187,126",12.9,551.1,596.7,45.6